version: "3.9"
services:
  worker:
    build: .
    environment:
      HANDLER: $HANDLER
      HELLBOT_SESSION: $HELLBOT_SESSION
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
